version: '3.8'

services:
  # SERVIÇO 1: GATEWAY
  gateway:
    build: ./gateway
    command: python -u gateway.py
    ports:
      - "9999:9999"
    depends_on:
      - engine-spark
      - engine-mpi 

  # SERVIÇO 2: ENGINE SPARK
  engine-spark:
    build: ./Spark
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "6000:6000"
    depends_on:
      - spark-master

  # SERVIÇO 3: ENGINE OMP/MPI (A NOVA!)
  engine-mpi:
    build: ./OMP_MPI 
    ports:
      - "6666:6666" 
    environment:
      - OMP_NUM_THREADS=2
      - NPROCS=3

  # SERVIÇO 4: O MASTER DO SPARK
  spark-master:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  # SERVIÇO 5: O WORKER DO SPARK
  spark-worker:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master