apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP  # You can change this to LoadBalancer if you need external access
  selector:
    app: gateway
  ports:
    - port: 9999
      targetPort: 9999