apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: pspd_gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
        env:
        - name: ELASTICSEARCH_URL
          value: "http://quickstart-es-http:9200" 
        - name: ELASTICSEARCH_API_KEY 
          value: "VFRjbEVaZ0JXR3I0czBlbmpfbmU6NHdvblhDbDdRay00bDBmWVdudkxKZw==" 

--- 

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - port: 9999
      targetPort: 9999