apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-mpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine-mpi
  template:
    metadata:
      labels:
        app: engine-mpi
    spec:
      containers:
      - name: engine-mpi
        image: pspd_mpi9:latest
        imagePullPolicy: Never
        env:
        - name: OMP_NUM_THREADS
          value: "2"
        - name: NPROCS
          value: "3"
        ports:
        - containerPort: 6666

---

apiVersion: v1
kind: Service
metadata:
  name: engine-mpi
spec:
  selector:
    app: engine-mpi
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
